In [4]:
import pandas as pd
import numpy as np

In [5]:


data = {
    "Customer_ID": [101, 102, 103, 104, 105, 106, 106, 108, 109, 110],
    "Name": ["Amit", "Riya", "Rahul", "Priya", "Amit", "Neha", "Neha", "Karan", "Simran", "Arjun"],
    "Age": [25, 30, np.nan, 28, 25, 35, 35, -5, 29, 200],
    "City": ["Delhi", "mumbai", "DELHI", "Pune", "Delhi", "Jaipur", "Jaipur", "pune", None, "Mumbai"],
    "Purchase_Amount": [1500, 2500, 1800, np.nan, 1500, 3200, 3200, 900, -500, 4100]
}

df = pd.DataFrame(data)

print("Original Customer Dataset")
display(df)

print("Dataset Shape:", df.shape)
print("Missing Values:")
print(df.isnull().sum())

Original Customer Dataset

   Customer_ID    Name    Age    City  Purchase_Amount
0          101    Amit   25.0   Delhi           1500.0
1          102    Riya   30.0  mumbai           2500.0
2          103   Rahul    NaN   DELHI           1800.0
3          104   Priya   28.0    Pune              NaN
4          105    Amit   25.0   Delhi           1500.0
5          106    Neha   35.0  Jaipur           3200.0
6          106    Neha   35.0  Jaipur           3200.0
7          108   Karan   -5.0    pune            900.0
8          109  Simran   29.0    None           -500.0
9          110   Arjun  200.0  Mumbai           4100.0

Dataset Shape: (10, 5)
Missing Values:
Customer_ID        0
Name               0
Age                1
City               1
Purchase_Amount    1
dtype: int64

In [6]:
# Data Quality Analysis

print("===== DATA QUALITY REPORT =====")

print("\n1. Dataset Information")
print("Total Rows:", df.shape[0])
print("Total Columns:", df.shape[1])

print("\n2. Missing Values")
print(df.isnull().sum())

print("\n3. Duplicate Rows")
print("Duplicate rows:", df.duplicated().sum())

print("\n4. Invalid Age Records")
print(df[(df["Age"] < 0) | (df["Age"] > 100)])

print("\n5. Negative Purchase Amounts")
print(df[df["Purchase_Amount"] < 0])

print("\n6. Data Types")
print(df.dtypes)

===== DATA QUALITY REPORT =====

1. Dataset Information
Total Rows: 10
Total Columns: 5

2. Missing Values
Customer_ID        0
Name               0
Age                1
City               1
Purchase_Amount    1
dtype: int64

3. Duplicate Rows
Duplicate rows: 1

4. Invalid Age Records
   Customer_ID   Name    Age    City  Purchase_Amount
7          108  Karan   -5.0    pune            900.0
9          110  Arjun  200.0  Mumbai           4100.0

5. Negative Purchase Amounts
   Customer_ID    Name   Age  City  Purchase_Amount
8          109  Simran  29.0  None           -500.0

6. Data Types
Customer_ID          int64
Name                object
Age                float64
City                object
Purchase_Amount    float64
dtype: object

In [7]:
# Create a copy of the original dataset
clean_df = df.copy()

# 1. Remove exact duplicate rows
clean_df = clean_df.drop_duplicates()

# 2. Standardize city names
clean_df["City"] = clean_df["City"].str.strip().str.title()

# 3. Replace invalid ages with missing values
clean_df.loc[
    (clean_df["Age"] < 0) | (clean_df["Age"] > 100), "Age"
] = np.nan

# 4. Replace negative purchase amounts with missing values
clean_df.loc[
    clean_df["Purchase_Amount"] < 0, "Purchase_Amount"
] = np.nan

# 5. Fill missing ages with the median
clean_df["Age"] = clean_df["Age"].fillna(
    clean_df["Age"].median()
)

# 6. Fill missing purchase amounts with the median
clean_df["Purchase_Amount"] = clean_df["Purchase_Amount"].fillna(
    clean_df["Purchase_Amount"].median()
)

# Display cleaned data
print("Cleaned Dataset")
display(clean_df)

print("Original shape:", df.shape)
print("Cleaned shape:", clean_df.shape)

Cleaned Dataset

   Customer_ID    Name   Age    City  Purchase_Amount
0          101    Amit  25.0   Delhi           1500.0
1          102    Riya  30.0  Mumbai           2500.0
2          103   Rahul  28.5   Delhi           1800.0
3          104   Priya  28.0    Pune           1800.0
4          105    Amit  25.0   Delhi           1500.0
5          106    Neha  35.0  Jaipur           3200.0
7          108   Karan  28.5    Pune            900.0
8          109  Simran  29.0    None           1800.0
9          110   Arjun  28.5  Mumbai           4100.0

Original shape: (10, 5)
Cleaned shape: (9, 5)

In [8]:
# Save the cleaned dataset as a CSV file
clean_df.to_csv("cleaned_customer_data.csv", index=False)

print("File saved successfully!")
print("Filename: cleaned_customer_data.csv")

File saved successfully!
Filename: cleaned_customer_data.csv

In [9]:
# Professional Data Quality Report

report = pd.DataFrame({
    "Metric": [
        "Total rows",
        "Total columns",
        "Exact duplicate rows",
        "Missing values (all columns)",
        "Invalid age records",
        "Negative purchase amounts",
        "Missing values after cleaning"
    ],
    "Before Cleaning": [
        len(df),
        len(df.columns),
        int(df.duplicated().sum()),
        int(df.isnull().sum().sum()),
        int(((df["Age"] < 0) | (df["Age"] > 100)).sum()),
        int((df["Purchase_Amount"] < 0).sum()),
        "Not applicable"
    ],
    "After Cleaning": [
        len(clean_df),
        len(clean_df.columns),
        int(clean_df.duplicated().sum()),
        int(clean_df.isnull().sum().sum()),
        int(((clean_df["Age"] < 0) | (clean_df["Age"] > 100)).sum()),
        int((clean_df["Purchase_Amount"] < 0).sum()),
        int(clean_df.isnull().sum().sum())
    ]
})

display(report)

# Save report as CSV
report.to_csv("data_quality_report.csv", index=False)

print("Data quality report saved successfully!")

                          Metric Before Cleaning  After Cleaning
0                     Total rows              10               9
1                  Total columns               5               5
2           Exact duplicate rows               1               0
3   Missing values (all columns)               3               1
4            Invalid age records               2               0
5      Negative purchase amounts               1               0
6  Missing values after cleaning  Not applicable               1

Data quality report saved successfully!